Animatron/player

src/anm/graphics/path.js
src/anm/graphics/segments.js

Fixed bugs in path calculations
@mcm69 or @shamansir please review and test whether it works.

Fixed bugs in path calculations

---

src/anm/animation/animation.js
src/anm/graphics/brush.js
src/anm/player.js
src/anm/render.js

Fix shadow scaling

---

examples/one-scene-input.html
src/anm/animation/animation.js
src/anm/animation/element.js
src/anm/events.js
src/anm/graphics/bounds.js
src/anm/graphics/path.js
src/anm/graphics/segments.js
src/anm/graphics/sheet.js
src/anm/graphics/text.js
src/anm/loader.js
src/anm/media/video.js
src/anm/player.js
src/anm/render.js
src/engine/dom-engine.js
src/import/animatron-importer.js
src/vendor/transform.js

@mcm69 @skavish Please review.
Now, it's winding tests for events, proper bounds tests etc.
P.S. Events are named in a beautiful way now, no requirement in creepy IDs anymore.

Interactivity is back, in a better way.

---

src/anm/animation/animation.js
src/anm/events.js
src/anm/media/audio.js
src/anm/media/video.js
src/anm/player.js
src/anm/ui/controls.js
src/import/animatron-importer.js

I'm still not sure if the audios would stop after their scene is complete, but at least they _work_ now.
@skavish @shamansir please review but do not merge yet

Fix clips containing audio/video

---

src/anm/graphics/path.js
src/anm/utils.js
src/engine/dom-engine.js
src/import/animatron-importer.js

see http://jsperf.com/anm-path-vs-path2d for free performance gains.

Use path2d

---

src/anm/animation/animation.js

one of those bugs that took forever to find and a second to fix /shrug

[PLAY-651] fix showing of preview for the second time

---

publish.js
src/anm/events.js
src/anm/interop/playerjs-io.js
src/anm/media/audio.js
src/anm/player.js
src/anm/render.js
src/anm/ui/controls.js
src/engine/dom-engine.js
src/main.js

@skavish @shamansir plz review

Support player.js (http://playerjs.io)

---

REQUIREMENTS
examples/one-scene-input.html
publish.js
src/anm/animation/animation.js
src/anm/animation/element.js
src/anm/loader.js
src/anm/player.js
src/anm/utils.js
src/import/animatron-importer.js
src/vendor/transform.js

Please do not merge yet, I plan some minor additions, but it's ok to review.

Interactivity

---

sandbox/interactivity-sandbox.html
sandbox/interactivity-sandbox.js
sandbox/sandbox.css
src/anm/animation/animation.js
src/anm/animation/element.js
src/anm/graphics/sheet.js
src/anm/media/video.js
src/anm/render.js
src/vendor/transform.js

A subject for review, but needs to be merged.

Point Transformation fixes for Interactivity

---

src/anm/animation/element.js

This fix is required for the `masks` PR.

Improve match-check to happen after the band-check

---

src/anm/animation/element.js

Now masks take the element's band into consideration + their rendering time now corresponds with their own jumps and repeat-modes.

Masks fixes

---

src/anm/animation/animation.js

Fixes for handling mouse events in Interactivity

---

src/anm/loader.js
src/anm/player.js
src/anm/ui/controls.js

With this option, one can hide the controls but still click to play/pause the animation.
@shamansir plz review

[PLAY-636] add controlsInvisible option

---

.travis.yml
README.md
package.json
spec/karma.conf.js
spec/orient-to-path.spec.js

To test if builds at TeamCity and Travis do fail.

One test to fail them all

---

examples/configuration.css
examples/configuration.html
examples/configuration.js

Already deployed: http://animatron.github.io/player/configuration/configuration.html

More options & style improvements for configuration helper

---

src/anm/analytics.js
src/anm/player.js
src/anm/utils.js

WIP. Player analytics

---

src/anm/analytics.js
src/engine/dom-engine.js

don't use setTimeout in analytics

---

src/main.js

export analytics to anm

---

src/anm/analytics.js

interactivity analytics

---

src/anm/analytics.js

`withCredentials` wouldn't work.
Also it's probably not the best way to use regex for cookies :/

send user when sendBeacon is not supported

---

src/anm/player.js

@shamansir pls merge. I completely didn't notice that I didn't add this line :(

fix /stats/report url

---

src/anm/media/audio.js
src/anm/media/video.js
src/import/animatron-importer.js

Support importing alternative formats for video

---

doc/embedding.md
publish.js
src/anm/loader.js
src/import/animatron-importer.js

Interactivity: Call actions from exported JSON

---

src/anm/analytics.js
src/anm/player.js

@shamansir @skavish pls review

Send analytic data on player detach

---

src/anm/media/video.js
src/engine/dom-engine.js

[PLAY-753] fixed. Video does not play

---

src/anm/animation/element.js
src/anm/graphics/sheet.js
src/anm/media/audio.js
src/anm/media/video.js
src/anm/resource_manager.js

Now elements use their own IDs for a subscriptions, instead of the ID of the Player.

Potential fix for resource manager subscriptions

---

src/anm/animation/element.js
src/anm/graphics/sheet.js
src/anm/media/audio.js
src/anm/media/video.js
src/anm/player.js

Follow-up for #346
In future, it would be better to get rid of these IDs, no doubts.

Fix loading thumbnails and improve passing subscription IDs

---

Jakefile
src/anm/analytics.js
src/anm/events.js
src/anm/player.js
src/anm/utils.js
src/main.js

Add animatron.local.js bundle without analytics

---

Jakefile
src/anm/analytics.js
src/anm/events.js
src/anm/player.js

@shamansir @skavish  pls review
https://github.com/Animatron/animatron-editor/pull/4773

Add interactivity analytics listener

---

src/anm/animation/element.js
src/anm/animation/tween.js
src/anm/constants.js
src/import/animatron-importer.js

[PLAY-723] - base implementation

[PLAY-723] - base implementation

---

src/anm/animation/animation.js
src/anm/animation/element.js
src/anm/animation/scene.js
src/anm/animation/timeline.js
src/anm/events.js
src/anm/player.js
src/anm/player_manager.js

* Timeline events: `JUMP`, `ITER`, `PAUSE`, `CONTINUE`
* Properly fire `START` / `END` on timeline
* Fix mask timing
* Properly apply scene timeline when rendering
* Switch scene when previous scene ended
* Improve events firing/handling mechanics

Refactor Timing, fixes and improvements

---

Jakefile
src/anm/animation/animation.js
src/anm/animation/element.js
src/anm/animation/scene.js
src/anm/animation/timeline.js
src/anm/events.js
src/anm/graphics/brush.js
src/anm/media/audio.js
src/anm/media/video.js
src/anm/player.js
src/anm/player_manager.js
src/anm/render.js
src/anm/ui/controls.js
src/import/animatron-importer.js

+ All of the rendering is now based on `dt` and timeline positions instead of global time;
+ Improved controls;

Animation and Scene now also contain Timeline and Player interacts with it

---

src/anm/animation/animation.js
src/engine/dom-engine.js

[PLAY-770] fixed. Google fonts should be supported by the player

---

src/anm/animation/animation.js

@shamansir pls review and merge

https url to google fonts

---

src/engine/dom-engine.js

this is just cherry pick to master, if you think it's fine then just merge it right away

added outline=none to all created canvases

---

src/anm/analytics.js

Enable analytics on production

---

.gitignore
spec/mouse.spec.js
spec/referenceImpl/mouseEvents/TestGroupsScene.java
spec/referenceImpl/mouseEvents/TestLayeredScene.java
spec/referenceImpl/mouseEvents/TestSimpleScene.java
spec/referenceImpl/mouseEvents/spec/Node.java
spec/referenceImpl/mouseEvents/test/TestLog.java
src/anm/events.js

Actually a lot more tests and one tiny, but important, fix.

Fixes for Interactivity & Mouse

---

spec/time.spec.js
src/anm/animation/animation.js
src/anm/animation/element.js
src/anm/animation/timeline.js

Some complex tests are still failing, I temporary disabled them, since fixes done here are more important.

Tests for timing in interactivity + some important fixes in calculating time

---

spec/time.spec.js
src/anm/animation/animation.js
src/anm/animation/element.js
src/anm/animation/scene.js
src/anm/animation/timeline.js
src/anm/events.js

```javascript
// Global:
animation.fireMessage('foo'); 
// which is a shortcut to:
animation.fire('message', 'foo');
animation.fireMessageAt(2.0, 'foo'); 
// which is a shortcut to:
animation.timeline.at(2.0, function() { animation.fireMessage('foo'); }); 
animation.onMessage('foo', function() { ... }); 
// which is a shortcut to:
animation.on('message', function(msg) { if (msg === 'foo') ... }); 
// Local:
element.fireMessage('foo'); 
// which is a shortcut to:
element.fire('message', 'foo');
element.fireMessageAt(2.0, 'foo'); 
// which is a shortcut to:
element.timeline.at(2.0, function() { element.fireMessage('foo') }); 
element.onMessage('foo', function() { ... }); 
// which is a shortcut to:
element.on('message', function(msg) { if (msg === 'foo') ... }); 
```

Interactivity: Messages

---

src/anm/animation/animation.js
src/anm/animation/scene.js
src/anm/animation/timeline.js
src/anm/media/audio.js
src/anm/media/video.js
src/anm/player.js
src/import/animatron-importer.js

Fixes for most of the present audio problems (especially Master Audio and stopping audio when animation played to the end).

Audio fixes

---

src/anm/media/audio.js

don't add audio extension if already present

---

src/anm/media/audio.js

Check audio type based on extension

---

publish.js

[EDIT-18088] fixed. Tall project gets cut on publish (embed).
